<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OpenEleven.Pes2013Pc</RootNamespace>
    <UserSecretsId>OpenEleven-Pes2013Pc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../../conf/server.pes2013pc.yaml" Link="conf\server.yaml"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OpenEleven.Server\OpenEleven.Server.csproj" />
    <ProjectReference Include="../OpenEleven.Profiles\Pes2013Pc\OpenEleven.Profiles.Pes2013Pc.csproj" />
  </ItemGroup>

</Project>