<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>OpenEleven.Pes2011Pc</RootNamespace>
    <UserSecretsId>OpenEleven-Pes2011Pc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="../../conf/server.pes2011pc.yaml" Link="conf\server.yaml"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OpenEleven.Server\OpenEleven.Server.csproj" />
    <ProjectReference Include="../OpenEleven.Profiles\Pes2011Pc\OpenEleven.Profiles.Pes2011Pc.csproj" />
  </ItemGroup>

</Project>